namespace T4Sample.Message
{
    /// <summary>
    /// Message name table to get message number.
    /// </summary>
    /// <remarks>
    /// This file was generated by T4.
    /// </remarks>
    public class MyMessage
    {
        /// <summary>The specified file is not found.</summary>
        public static string FileNotFound = "M0001";

        /// <summary>The file path is not specified.</summary>
        public static string FileNotSpecified = "M0002";

        /// <summary>The operation has been completed.</summary>
        public static string OperationCompleted = "M0003";

    }
}